<?php
define("__HOST__","127.0.0.1");
define("__PORT__",3000);
define("__USER__","root");
define("__PASS__","");
define("__DB__","northwind");
define("__table_Name__","items");
define("__RECORDS_PER_PAGE__",3);
define("__Debug__Mode__",0);